# Generated by Django 6.0.6 on 2026-07-15 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18, message='You must be at least 18 years old.'), django.core.validators.MaxValueValidator(120, message='Please enter a valid age.')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
